# Generated by Django 5.2.7 on 2025-11-01 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('depoimento', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('estrelas', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo', models.CharField(default='Soluções Profissionais em Refrigeração', help_text='Título principal da seção hero', max_length=200)),
                ('hero_subtitulo', models.TextField(default='Especialistas em instalação, manutenção e reparo de sistemas de refrigeração comercial e industrial', help_text='Subtítulo explicativo da seção hero')),
                ('hero_cta_texto', models.CharField(default='Solicitar Orçamento', help_text='Texto do botão principal', max_length=50)),
                ('hero_cta_link', models.CharField(default='#contato', help_text='Link do botão principal', max_length=200)),
                ('hero_imagem', models.ImageField(blank=True, help_text='Imagem de fundo da seção hero', null=True, upload_to='hero/')),
                ('sobre_titulo', models.CharField(default='Sobre a Clima Ar Ne Refrigeração', help_text='Título da seção sobre', max_length=200)),
                ('sobre_texto', models.TextField(default='Com mais de 10 anos de experiência no mercado de refrigeração, a Clima Ar Ne Refrigeração é especializada em soluções completas para sistemas de refrigeração comercial e industrial. Nossa equipe de técnicos certificados oferece serviços de instalação, manutenção preventiva e corretiva, garantindo máxima eficiência e durabilidade dos seus equipamentos.', help_text='Texto principal da seção sobre')),
                ('sobre_imagem', models.ImageField(blank=True, help_text='Imagem da seção sobre', null=True, upload_to='sobre/')),
                ('contato_titulo', models.CharField(default='Fale Conosco', help_text='Título da seção contato', max_length=200)),
                ('contato_descricao', models.TextField(default='Entre em contato para um orçamento personalizado. Nossa equipe está pronta para atender suas necessidades de refrigeração.', help_text='Descrição da seção contato')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteúdo da Landing Page',
                'verbose_name_plural': 'Conteúdo da Landing Page',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='default-icon.svg', help_text='Nome do arquivo do ícone SVG', max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contatado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.tiposervico')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
