# Generated by Django 5.2.7 on 2025-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='email',
            field=models.EmailField(default='contato@Clima Ar Ne Refrigeração.com.br', help_text='E-mail de contato principal', max_length=254),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='endereco',
            field=models.CharField(default='São Paulo, SP', help_text='Endereço da empresa', max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='telefone',
            field=models.CharField(default='(11) 99999-9999', help_text='Número de telefone principal', max_length=20),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='whatsapp',
            field=models.CharField(default='5511999999999', help_text='Número do WhatsApp (formato: 5511999999999)', max_length=20),
        ),
    ]
