# Generated by Django 5.2.7 on 2025-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landingcontent_email_landingcontent_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='area_atendimento_texto',
            field=models.CharField(default='Atendemos toda a Grande São Paulo', help_text='Área de cobertura/atendimento', max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='atendimento_emergencias_texto',
            field=models.CharField(default='Atendimento 24h para emergências', help_text='Mensagem destacando o atendimento de emergências', max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='horario_emergencias',
            field=models.CharField(default='Emergências: 24h', help_text='Horário de atendimento para emergências', max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='horario_sabado',
            field=models.CharField(default='Sábado: 8h às 12h', help_text='Horário de funcionamento aos sábados', max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='horario_semana',
            field=models.CharField(default='Segunda a Sexta: 8h às 18h', help_text='Horário de funcionamento em dias úteis', max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='tempo_resposta_texto',
            field=models.CharField(default='Resposta em até 2 horas', help_text='Mensagem sobre tempo de resposta típico', max_length=200),
        ),
    ]
