# Generated by Django 5.2.7 on 2025-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_landingcontent_area_atendimento_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Logo para o footer (preferir versão clara ou monocromática, sem necessidade de inverter)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='logo_header',
            field=models.ImageField(blank=True, help_text='Logo para o header (preferir versão com bom contraste em fundo azul escuro)', null=True, upload_to='branding/'),
        ),
    ]
