# Generated by Django 5.2.7 on 2025-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_landingcontent_logo_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL da página no Facebook', null=True),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL do perfil no Instagram', null=True),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL da página no LinkedIn', null=True),
        ),
    ]
