# Generated by Django 5.2.7 on 2025-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_landingcontent_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='whatsapp_boas_vindas',
            field=models.CharField(default='Olá! Gostaria de solicitar um orçamento para serviços de refrigeração.', help_text='Mensagem de boas-vindas usada ao abrir o WhatsApp via wa.me', max_length=255),
        ),
    ]
