# Generated by Django 5.2.7 on 2025-11-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_landingcontent_whatsapp_boas_vindas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do card (ex.: Clientes atendidos)', max_length=100)),
                ('valor', models.CharField(help_text='Valor/quantidade (ex.: 150+, 10 anos)', max_length=50)),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional abaixo do título', max_length=200)),
                ('icone', models.CharField(blank=True, help_text='Nome do arquivo do ícone SVG (opcional)', max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landing_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='landing.landingcontent')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
