# Generated by Django 5.2.7 on 2025-11-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_estatistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingcontent',
            name='contato_descricao',
            field=models.TextField(blank=True, help_text='Descrição da seção contato'),
        ),
    ]
